// <auto-generated />
using System;
using AuthServer.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthServer.TestIdentityProvider.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    [Migration("20251119210911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthServer.Entities.AuthenticationContextReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthenticationContextReference");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthenticationMethodReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AuthenticationMethodReference");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "pwd"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mfa"
                        },
                        new
                        {
                            Id = 3,
                            Name = "sms"
                        },
                        new
                        {
                            Id = 4,
                            Name = "face"
                        },
                        new
                        {
                            Id = 5,
                            Name = "fpt"
                        },
                        new
                        {
                            Id = 6,
                            Name = "geo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "iris"
                        },
                        new
                        {
                            Id = 8,
                            Name = "kba"
                        },
                        new
                        {
                            Id = 9,
                            Name = "mca"
                        },
                        new
                        {
                            Id = 10,
                            Name = "otp"
                        },
                        new
                        {
                            Id = 11,
                            Name = "pin"
                        },
                        new
                        {
                            Id = 12,
                            Name = "hwk"
                        },
                        new
                        {
                            Id = 13,
                            Name = "pop"
                        },
                        new
                        {
                            Id = 14,
                            Name = "swk"
                        },
                        new
                        {
                            Id = 15,
                            Name = "retina"
                        },
                        new
                        {
                            Id = 16,
                            Name = "rba"
                        },
                        new
                        {
                            Id = 17,
                            Name = "sc"
                        },
                        new
                        {
                            Id = 18,
                            Name = "tel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "user"
                        },
                        new
                        {
                            Id = 20,
                            Name = "vbm"
                        },
                        new
                        {
                            Id = 21,
                            Name = "wia"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AuthenticationContextReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAuthTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAuthTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationContextReferenceId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SessionId");

                    b.ToTable("AuthorizationGrant");

                    b.HasDiscriminator().HasValue("AuthorizationGrant");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizationGrantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConsentId")
                        .HasColumnType("int");

                    b.Property<int>("ConsentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationGrantId");

                    b.HasIndex("ConsentId");

                    b.ToTable("AuthorizationGrantConsent");

                    b.HasDiscriminator<int>("ConsentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizeMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("AuthorizeMessage");
                });

            modelBuilder.Entity("AuthServer.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Claim");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "name"
                        },
                        new
                        {
                            Id = 2,
                            Name = "given_name"
                        },
                        new
                        {
                            Id = 3,
                            Name = "family_name"
                        },
                        new
                        {
                            Id = 4,
                            Name = "middle_name"
                        },
                        new
                        {
                            Id = 5,
                            Name = "nickname"
                        },
                        new
                        {
                            Id = 6,
                            Name = "preferred_username"
                        },
                        new
                        {
                            Id = 7,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 8,
                            Name = "picture"
                        },
                        new
                        {
                            Id = 9,
                            Name = "website"
                        },
                        new
                        {
                            Id = 10,
                            Name = "email"
                        },
                        new
                        {
                            Id = 11,
                            Name = "email_verified"
                        },
                        new
                        {
                            Id = 12,
                            Name = "gender"
                        },
                        new
                        {
                            Id = 13,
                            Name = "birthdate"
                        },
                        new
                        {
                            Id = 14,
                            Name = "zoneinfo"
                        },
                        new
                        {
                            Id = 15,
                            Name = "locale"
                        },
                        new
                        {
                            Id = 16,
                            Name = "phone_number"
                        },
                        new
                        {
                            Id = 17,
                            Name = "phone_number_verified"
                        },
                        new
                        {
                            Id = 18,
                            Name = "address"
                        },
                        new
                        {
                            Id = 19,
                            Name = "updated_at"
                        },
                        new
                        {
                            Id = 20,
                            Name = "roles"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessTokenExpiration")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorizationCodeExpiration")
                        .HasColumnType("int");

                    b.Property<string>("BackchannelLogoutUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DPoPNonceExpiration")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultMaxAge")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceCodeExpiration")
                        .HasColumnType("int");

                    b.Property<int?>("IdTokenEncryptedResponseAlg")
                        .HasColumnType("int");

                    b.Property<int?>("IdTokenEncryptedResponseEnc")
                        .HasColumnType("int");

                    b.Property<int?>("IdTokenSignedResponseAlg")
                        .HasColumnType("int");

                    b.Property<string>("InitiateLoginUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Jwks")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JwksExpiration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JwksExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwksUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LogoUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PolicyUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RefreshTokenExpiration")
                        .HasColumnType("int");

                    b.Property<int?>("RequestObjectEncryptionAlg")
                        .HasColumnType("int");

                    b.Property<int?>("RequestObjectEncryptionEnc")
                        .HasColumnType("int");

                    b.Property<int?>("RequestObjectSigningAlg")
                        .HasColumnType("int");

                    b.Property<int?>("RequestUriExpiration")
                        .HasColumnType("int");

                    b.Property<bool>("RequireConsent")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireDPoPBoundAccessTokens")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireIdTokenClaims")
                        .HasColumnType("bit");

                    b.Property<bool>("RequirePushedAuthorizationRequests")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireReferenceToken")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSignedRequestObject")
                        .HasColumnType("bit");

                    b.Property<int?>("SecretExpiration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SecretExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecretHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SectorIdentifierId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectType")
                        .HasColumnType("int");

                    b.Property<int?>("TokenEndpointAuthEncryptionAlg")
                        .HasColumnType("int");

                    b.Property<int?>("TokenEndpointAuthEncryptionEnc")
                        .HasColumnType("int");

                    b.Property<int>("TokenEndpointAuthMethod")
                        .HasColumnType("int");

                    b.Property<int?>("TokenEndpointAuthSigningAlg")
                        .HasColumnType("int");

                    b.Property<string>("TosUri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserinfoEncryptedResponseAlg")
                        .HasColumnType("int");

                    b.Property<int?>("UserinfoEncryptedResponseEnc")
                        .HasColumnType("int");

                    b.Property<int?>("UserinfoSignedResponseAlg")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientUri");

                    b.HasIndex("SectorIdentifierId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.ClientAuthenticationContextReference", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AuthenticationContextReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "AuthenticationContextReferenceId");

                    b.HasIndex("AuthenticationContextReferenceId");

                    b.ToTable("ClientAuthenticationContextReference");
                });

            modelBuilder.Entity("AuthServer.Entities.Code", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CodeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RawValue")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Code");

                    b.HasDiscriminator<int>("CodeType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.Consent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConsentType")
                        .HasColumnType("int");

                    b.Property<string>("SubjectIdentifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SubjectIdentifierId");

                    b.ToTable("Consent");

                    b.HasDiscriminator<int>("ConsentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("AuthServer.Entities.GrantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GrantType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "authorization_code"
                        },
                        new
                        {
                            Id = 2,
                            Name = "client_credentials"
                        },
                        new
                        {
                            Id = 3,
                            Name = "refresh_token"
                        },
                        new
                        {
                            Id = 4,
                            Name = "urn:ietf:params:oauth:grant-type:device_code"
                        },
                        new
                        {
                            Id = 5,
                            Name = "urn:ietf:params:oauth:grant-type:token-exchange"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Nonce", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HashedValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NonceType")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nonce");

                    b.HasDiscriminator<int>("NonceType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.PostLogoutRedirectUri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PostLogoutRedirectUri");
                });

            modelBuilder.Entity("AuthServer.Entities.RedirectUri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("RedirectUri");
                });

            modelBuilder.Entity("AuthServer.Entities.RequestUri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("RequestUri");
                });

            modelBuilder.Entity("AuthServer.Entities.ResponseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResponseType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "code"
                        },
                        new
                        {
                            Id = 2,
                            Name = "none"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.Scope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scope");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "openid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "offline_access"
                        },
                        new
                        {
                            Id = 3,
                            Name = "profile"
                        },
                        new
                        {
                            Id = 4,
                            Name = "address"
                        },
                        new
                        {
                            Id = 5,
                            Name = "email"
                        },
                        new
                        {
                            Id = 6,
                            Name = "phone"
                        },
                        new
                        {
                            Id = 7,
                            Name = "authserver:userinfo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "authserver:register"
                        },
                        new
                        {
                            Id = 9,
                            Name = "grant_management_query"
                        },
                        new
                        {
                            Id = 10,
                            Name = "grant_management_revoke"
                        });
                });

            modelBuilder.Entity("AuthServer.Entities.SectorIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Uri")
                        .IsUnique();

                    b.ToTable("SectorIdentifier");
                });

            modelBuilder.Entity("AuthServer.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectIdentifierId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectIdentifierId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("AuthServer.Entities.SubjectIdentifier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("SubjectIdentifier");
                });

            modelBuilder.Entity("AuthServer.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Jkt")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Scope")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectActor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SubjectMayAct")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TokenType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Token");

                    b.HasDiscriminator<int>("TokenType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuthServer.Entities.UserCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceCodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCodeId")
                        .IsUnique();

                    b.HasIndex("Value");

                    b.ToTable("UserCode");
                });

            modelBuilder.Entity("AuthorizationGrantAuthenticationMethodReference", b =>
                {
                    b.Property<int>("AuthenticationMethodReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationGrantId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AuthenticationMethodReferenceId", "AuthorizationGrantId");

                    b.HasIndex("AuthorizationGrantId");

                    b.ToTable("AuthorizationGrantAuthenticationMethodReference");
                });

            modelBuilder.Entity("ClientGrantType", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GrantTypeId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "GrantTypeId");

                    b.HasIndex("GrantTypeId");

                    b.ToTable("ClientGrantType");
                });

            modelBuilder.Entity("ClientResponseType", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResponseTypeId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "ResponseTypeId");

                    b.HasIndex("ResponseTypeId");

                    b.ToTable("ClientResponseType");
                });

            modelBuilder.Entity("ClientScope", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ClientScope");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationCodeGrant", b =>
                {
                    b.HasBaseType("AuthServer.Entities.AuthorizationGrant");

                    b.HasDiscriminator().HasValue("AuthorizationCodeGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.DeviceCodeGrant", b =>
                {
                    b.HasBaseType("AuthServer.Entities.AuthorizationGrant");

                    b.HasDiscriminator().HasValue("DeviceCodeGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantClaimConsent", b =>
                {
                    b.HasBaseType("AuthServer.Entities.AuthorizationGrantConsent");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantScopeConsent", b =>
                {
                    b.HasBaseType("AuthServer.Entities.AuthorizationGrantConsent");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationCode", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Code");

                    b.Property<string>("AuthorizationCodeGrantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AuthorizationCodeGrantId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AuthServer.Entities.DeviceCode", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Code");

                    b.Property<int>("CurrentInterval")
                        .HasColumnType("int");

                    b.Property<string>("DeviceCodeGrantId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LatestPoll")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.HasIndex("DeviceCodeGrantId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AuthServer.Entities.ClaimConsent", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Consent");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.HasIndex("ClaimId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AuthServer.Entities.ScopeConsent", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Consent");

                    b.Property<int>("ScopeId")
                        .HasColumnType("int");

                    b.HasIndex("ScopeId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantNonce", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Nonce");

                    b.Property<string>("AuthorizationGrantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AuthorizationGrantId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AuthServer.Entities.DPoPNonce", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Nonce");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasIndex("ClientId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AuthServer.Entities.ClientToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Token");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("ClientId");
                });

            modelBuilder.Entity("AuthServer.Entities.GrantToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.Token");

                    b.Property<string>("AuthorizationGrantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("AuthorizationGrantId");
                });

            modelBuilder.Entity("AuthServer.Entities.ClientAccessToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.ClientToken");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("AuthServer.Entities.RegistrationToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.ClientToken");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("AuthServer.Entities.GrantAccessToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.GrantToken");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("AuthServer.Entities.RefreshToken", b =>
                {
                    b.HasBaseType("AuthServer.Entities.GrantToken");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrant", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthenticationContextReference", "AuthenticationContextReference")
                        .WithMany("AuthorizationGrants")
                        .HasForeignKey("AuthenticationContextReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("AuthorizationGrants")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Session", "Session")
                        .WithMany("AuthorizationGrants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AuthenticationContextReference");

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantConsent", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthorizationGrant", "AuthorizationGrant")
                        .WithMany("AuthorizationGrantConsents")
                        .HasForeignKey("AuthorizationGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Consent", "Consent")
                        .WithMany("AuthorizationGrantConsents")
                        .HasForeignKey("ConsentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorizationGrant");

                    b.Navigation("Consent");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizeMessage", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("AuthorizeMessages")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.Client", b =>
                {
                    b.HasOne("AuthServer.Entities.SectorIdentifier", "SectorIdentifier")
                        .WithMany("Clients")
                        .HasForeignKey("SectorIdentifierId");

                    b.Navigation("SectorIdentifier");
                });

            modelBuilder.Entity("AuthServer.Entities.ClientAuthenticationContextReference", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthenticationContextReference", "AuthenticationContextReference")
                        .WithMany("ClientAuthenticationContextReferences")
                        .HasForeignKey("AuthenticationContextReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("ClientAuthenticationContextReferences")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AuthenticationContextReference");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.Consent", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("Consents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.SubjectIdentifier", "SubjectIdentifier")
                        .WithMany("Consents")
                        .HasForeignKey("SubjectIdentifierId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SubjectIdentifier");
                });

            modelBuilder.Entity("AuthServer.Entities.Contact", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.PostLogoutRedirectUri", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("PostLogoutRedirectUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.RedirectUri", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("RedirectUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.RequestUri", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("RequestUris")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.Session", b =>
                {
                    b.HasOne("AuthServer.Entities.SubjectIdentifier", "SubjectIdentifier")
                        .WithMany("Sessions")
                        .HasForeignKey("SubjectIdentifierId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("SubjectIdentifier");
                });

            modelBuilder.Entity("AuthServer.Entities.UserCode", b =>
                {
                    b.HasOne("AuthServer.Entities.DeviceCode", "DeviceCode")
                        .WithOne()
                        .HasForeignKey("AuthServer.Entities.UserCode", "DeviceCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCode");
                });

            modelBuilder.Entity("AuthorizationGrantAuthenticationMethodReference", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthenticationMethodReference", null)
                        .WithMany()
                        .HasForeignKey("AuthenticationMethodReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.AuthorizationGrant", null)
                        .WithMany()
                        .HasForeignKey("AuthorizationGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientGrantType", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.GrantType", null)
                        .WithMany()
                        .HasForeignKey("GrantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientResponseType", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.ResponseType", null)
                        .WithMany()
                        .HasForeignKey("ResponseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClientScope", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthServer.Entities.Scope", null)
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationCode", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthorizationCodeGrant", "AuthorizationCodeGrant")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("AuthorizationCodeGrantId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AuthorizationCodeGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.DeviceCode", b =>
                {
                    b.HasOne("AuthServer.Entities.DeviceCodeGrant", "DeviceCodeGrant")
                        .WithMany("DeviceCodes")
                        .HasForeignKey("DeviceCodeGrantId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.Navigation("DeviceCodeGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.ClaimConsent", b =>
                {
                    b.HasOne("AuthServer.Entities.Claim", "Claim")
                        .WithMany("ClaimConsents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("AuthServer.Entities.ScopeConsent", b =>
                {
                    b.HasOne("AuthServer.Entities.Scope", "Scope")
                        .WithMany("ScopeConsents")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrantNonce", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthorizationGrant", "AuthorizationGrant")
                        .WithMany("Nonces")
                        .HasForeignKey("AuthorizationGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorizationGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.DPoPNonce", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("Nonces")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.ClientToken", b =>
                {
                    b.HasOne("AuthServer.Entities.Client", "Client")
                        .WithMany("ClientTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthServer.Entities.GrantToken", b =>
                {
                    b.HasOne("AuthServer.Entities.AuthorizationGrant", "AuthorizationGrant")
                        .WithMany("GrantTokens")
                        .HasForeignKey("AuthorizationGrantId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AuthorizationGrant");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthenticationContextReference", b =>
                {
                    b.Navigation("AuthorizationGrants");

                    b.Navigation("ClientAuthenticationContextReferences");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationGrant", b =>
                {
                    b.Navigation("AuthorizationGrantConsents");

                    b.Navigation("GrantTokens");

                    b.Navigation("Nonces");
                });

            modelBuilder.Entity("AuthServer.Entities.Claim", b =>
                {
                    b.Navigation("ClaimConsents");
                });

            modelBuilder.Entity("AuthServer.Entities.Client", b =>
                {
                    b.Navigation("AuthorizationGrants");

                    b.Navigation("AuthorizeMessages");

                    b.Navigation("ClientAuthenticationContextReferences");

                    b.Navigation("ClientTokens");

                    b.Navigation("Consents");

                    b.Navigation("Contacts");

                    b.Navigation("Nonces");

                    b.Navigation("PostLogoutRedirectUris");

                    b.Navigation("RedirectUris");

                    b.Navigation("RequestUris");
                });

            modelBuilder.Entity("AuthServer.Entities.Consent", b =>
                {
                    b.Navigation("AuthorizationGrantConsents");
                });

            modelBuilder.Entity("AuthServer.Entities.Scope", b =>
                {
                    b.Navigation("ScopeConsents");
                });

            modelBuilder.Entity("AuthServer.Entities.SectorIdentifier", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("AuthServer.Entities.Session", b =>
                {
                    b.Navigation("AuthorizationGrants");
                });

            modelBuilder.Entity("AuthServer.Entities.SubjectIdentifier", b =>
                {
                    b.Navigation("Consents");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AuthServer.Entities.AuthorizationCodeGrant", b =>
                {
                    b.Navigation("AuthorizationCodes");
                });

            modelBuilder.Entity("AuthServer.Entities.DeviceCodeGrant", b =>
                {
                    b.Navigation("DeviceCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
