name: CI

on:
  pull_request:
  push:
    branches:
      - main
  
env:
  DOTNET_NOLOGO: true

jobs:
  build_solution:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Install tools
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet tool install --global dotnet-sonarscanner
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'zulu'
    - name: Restore dependencies
      run: dotnet restore authserver.sln
    - name: Analyze
      env:
        ConnectionStrings__Default: ${{ secrets.DATABASE_CONNECTION }}
      run: |
        dotnet-sonarscanner begin /k:"jokk-itu_authserver-framework" /o:"jokk-itu" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml /d:sonar.scanner.skipJreProvisioning=true
        dotnet build authserver.sln --no-restore
        dotnet-coverage collect 'dotnet test authserver.sln --no-build' -f xml  -o 'coverage.xml'
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
  
  build_documentation:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install and Build
        run: |
          cd doc
          npm install
          npm run build